import test from "node:test";
import assert from "node:assert/strict";

import * as knowledgeEngine from "../src/knowledge-engine.mjs";

const {
  classifyKnowledge,
  isNewUpdate,
  mergeKnowledgeUpdates,
  toKnowledgeUpdate,
} = knowledgeEngine;

test("将 RAG 更新归入信息与知识模块", () => {
  const modules = classifyKnowledge({
    title: "RAG retrieval and reranking improvements",
    summary: "New vector search and embedding options for retrieval-augmented generation.",
  });

  assert.deepEqual(modules, ["knowledge"]);
});

test("七天内的更新展示为新更新", () => {
  const now = new Date("2026-08-06T08:00:00.000Z");

  assert.equal(isNewUpdate("2026-08-01T08:00:00.000Z", now), true);
  assert.equal(isNewUpdate("2026-07-29T08:00:00.000Z", now), false);
});

test("合并更新时按来源去重并保留最新条目", () => {
  const current = [
    {
      id: "existing",
      sourceUrl: "https://example.com/existing",
      publishedAt: "2026-08-01T08:00:00.000Z",
    },
  ];
  const incoming = [
    {
      id: "replacement",
      sourceUrl: "https://example.com/existing",
      publishedAt: "2026-08-05T08:00:00.000Z",
    },
    {
      id: "new-item",
      sourceUrl: "https://example.com/new",
      publishedAt: "2026-08-03T08:00:00.000Z",
    },
  ];

  assert.deepEqual(
    mergeKnowledgeUpdates(current, incoming).map((item) => item.id),
    ["replacement", "new-item"],
  );
});

test("未知的持续性 AI 能力可自动扩展学习框架且不会重复添加", () => {
  assert.equal(typeof knowledgeEngine.mergeFrameworkExtensions, "function");
  const coreModule = {
    id: "foundations",
    number: "01",
    name: "AI 与模型基础",
    shortName: "模型基础",
    lessons: [],
  };
  const candidate = {
    id: "multimodal-runtime",
    name: "实时多模态交互",
    shortName: "多模态交互",
    description: "理解语音、图像与实时响应如何组合为新的 AI 交互能力。",
    lesson: {
      id: "realtime-multimodal",
      name: "实时多模态交互",
      subtitle: "让语音、图像和文本在同一轮交互中协同工作",
      beginnerSummary: "它让 AI 能在同一次交互里理解和响应多种输入。",
      whyItMatters: "它改变了用户与 AI 协作的方式。",
      definition: "一种面向实时多种输入的 AI 能力。",
      principle: "系统协调多种输入与输出通道。",
      example: "用户语音提问并上传图片获得回答。",
      caseStudy: { scenario: "用户通过语音和图片请求现场协助。", steps: ["识别输入", "理解上下文", "返回结果"], takeaway: "应确保多模态输入一致。" },
      practice: ["定义输入范围", "设计降级", "验证隐私"],
      pitfalls: ["忽略延迟", "输入错配"],
      related: ["语音", "图像"],
    },
  };

  const firstMerge = knowledgeEngine.mergeFrameworkExtensions([coreModule], [candidate], new Date("2026-08-10T00:00:00.000Z"));
  const secondMerge = knowledgeEngine.mergeFrameworkExtensions(firstMerge, [candidate], new Date("2026-08-10T00:00:00.000Z"));

  assert.equal(firstMerge.length, 2);
  assert.equal(firstMerge[1].number, "02");
  assert.equal(firstMerge[1].autoGenerated, true);
  assert.equal(firstMerge[1].lessons.length, 1);
  assert.equal(secondMerge.length, 2);
  assert.equal(secondMerge[1].lessons.length, 1);
});

test("刷新任务可将经语义识别的更新归入指定模块", () => {
  const update = toKnowledgeUpdate({
    title: "RAG retrieval update",
    summary: "A public update about vector retrieval for AI systems.",
    sourceName: "Example source",
    sourceType: "official",
    sourceUrl: "https://example.com/evaluation",
    publishedAt: "2026-08-10T00:00:00.000Z",
    modules: ["operations"],
    lessonId: "evaluation",
    learningConnection: "这条更新补充了效果评估模块中如何持续验证 AI 能力的知识。",
  }, new Date("2026-08-10T12:00:00.000Z"));

  assert.deepEqual(update.modules, ["operations"]);
  assert.match(update.id, /^operations-/);
  assert.equal(update.lessonId, "evaluation");
  assert.equal(update.learningConnection, "这条更新补充了效果评估模块中如何持续验证 AI 能力的知识。");
});
