const MODULE_KEYWORDS = {
  foundations: [
    "large language model",
    "llm",
    "transformer",
    "pretraining",
    "fine-tuning",
    "inference",
    "reasoning model",
  ],
  input: [
    "token",
    "prompt",
    "intent",
    "moderation",
    "multimodal input",
    "speech",
    "image input",
  ],
  knowledge: [
    "rag",
    "retrieval",
    "reranking",
    "embedding",
    "vector search",
    "context window",
    "memory",
    "knowledge base",
  ],
  agent: [
    "agent",
    "tool calling",
    "function calling",
    "planning",
    "react",
    "reflection",
    "multi-agent",
  ],
  output: [
    "structured output",
    "json schema",
    "generation",
    "decoding",
    "output safety",
    "response format",
  ],
  operations: [
    "evaluation",
    "eval",
    "observability",
    "latency",
    "cost",
    "monitoring",
    "release",
  ],
};

const NEW_UPDATE_WINDOW_MS = 7 * 24 * 60 * 60 * 1000;

function textOf({ title = "", summary = "" }) {
  return `${title} ${summary}`.toLocaleLowerCase();
}

function publishedTime(item) {
  const time = Date.parse(item.publishedAt);
  return Number.isNaN(time) ? 0 : time;
}

export function classifyKnowledge(item) {
  const text = textOf(item);
  const scoreByModule = Object.entries(MODULE_KEYWORDS)
    .map(([module, keywords]) => ({
      module,
      score: keywords.reduce(
        (score, keyword) => score + Number(text.includes(keyword)),
        0,
      ),
    }))
    .filter(({ score }) => score > 0)
    .sort((left, right) => right.score - left.score);

  return scoreByModule.length ? [scoreByModule[0].module] : ["foundations"];
}

export function isNewUpdate(publishedAt, now = new Date()) {
  const publishedMs = Date.parse(publishedAt);
  if (Number.isNaN(publishedMs)) return false;

  const age = now.getTime() - publishedMs;
  return age >= 0 && age <= NEW_UPDATE_WINDOW_MS;
}

export function mergeKnowledgeUpdates(current = [], incoming = []) {
  const latestBySource = new Map();

  for (const item of [...current, ...incoming]) {
    if (!item.sourceUrl) continue;
    const existing = latestBySource.get(item.sourceUrl);
    if (!existing || publishedTime(item) > publishedTime(existing)) {
      latestBySource.set(item.sourceUrl, item);
    }
  }

  return [...latestBySource.values()].sort(
    (left, right) => publishedTime(right) - publishedTime(left),
  );
}

function nextModuleNumber(modules) {
  const highest = modules.reduce((number, module) => {
    const value = Number.parseInt(module.number, 10);
    return Number.isFinite(value) ? Math.max(number, value) : number;
  }, 0);
  return String(highest + 1).padStart(2, "0");
}

function validExtension(candidate) {
  return candidate
    && /^[a-z0-9-]{3,48}$/.test(candidate.id || "")
    && typeof candidate.name === "string"
    && typeof candidate.shortName === "string"
    && typeof candidate.description === "string"
    && candidate.lesson?.id
    && candidate.lesson?.name;
}

export function mergeFrameworkExtensions(modules = [], candidates = [], now = new Date()) {
  const merged = modules.map((module) => ({
    ...module,
    lessons: [...(module.lessons || [])],
  }));

  candidates.filter(validExtension).forEach((candidate) => {
    const existing = merged.find((module) => module.id === candidate.id);
    if (existing) {
      if (existing.autoGenerated && !existing.lessons.some((lesson) => lesson.id === candidate.lesson.id)) {
        existing.lessons.push(candidate.lesson);
      }
      return;
    }

    merged.push({
      id: candidate.id,
      number: nextModuleNumber(merged),
      name: candidate.name.trim(),
      shortName: candidate.shortName.trim(),
      description: candidate.description.trim(),
      accent: "foundation",
      autoGenerated: true,
      addedAt: now.toISOString(),
      lessons: [candidate.lesson],
    });
  });

  return merged;
}

export function toKnowledgeUpdate(entry, now = new Date()) {
  const assignedModules = Array.isArray(entry.modules)
    ? entry.modules.filter((module) => typeof module === "string" && module.trim())
    : [];
  const modules = assignedModules.length ? assignedModules : classifyKnowledge(entry);
  const sourceUrl = entry.sourceUrl || entry.link;
  const publishedAt = entry.publishedAt || now.toISOString();

  return {
    id: `${modules[0]}-${encodeURIComponent(sourceUrl)}`,
    title: entry.title.trim(),
    summary: entry.summary.trim(),
    lessonId: typeof entry.lessonId === "string" ? entry.lessonId : "",
    learningConnection: typeof entry.learningConnection === "string" ? entry.learningConnection.trim() : "",
    sourceUrl,
    sourceName: entry.sourceName,
    sourceType: entry.sourceType,
    publishedAt,
    modules,
    isNew: isNewUpdate(publishedAt, now),
  };
}
